### ISSUE TITLE
Issue Tracker for Uno

### ISSUE THREAD

**Issue by Villagers654** [FrequencyX4/Fate#47]
General Issue Tracked for Uno's various problems as I encounter them

Known Issues:
- Turn timeout will sometimes happen instanteously 
- Color changing dropdowns will appear for everyone instead of just the player who uses them
- Sometimes people will win without having 0 cards
- Draw 4 and 2 cards don't skip the next player's turn
- Wild cards are called "color changers"
- Some messages will appear out of order (especially "x player was skipped for inactivity", when a player is skipped sooner than they should've been)
- Game will sometimes just end, possibly due to "spam" drawing

Enhancements

- .uno cards or .card command
- Uno perm should be unlocked to general members somehow and made less spammy (threads?)
- Players should be prevented from drawing if they have a possible move

**Comment by FrequencyX4** [comment]
colors work no worries on that

the perm lock is due to how spammy it is so that only mods can start games. this is also the only interactive game in the bot

the rest I'll fix soon™️

**Comment by Villagers654** [comment]
I haven't exactly been able to reproduce but I was in a game where someone straight up played a blue +2 on a yellow 7, so colors don't exactly work 100% properly

**Comment by FrequencyX4** [comment]
it might be an issue with the draw 4 card

**Comment by Villagers654** [comment]
that sounds about right

**Comment by Villagers654** [comment]
also mikey have you implemented wild cards

**Comment by FrequencyX4** [comment]
what are those..

**Comment by Villagers654** [comment]
LMAO

**Comment by Villagers654** [comment]
![image](https://user-images.githubusercontent.com/74448585/148629053-ef056ebb-5208-4e79-ba38-5537b828ba92.png)
draw 4 not reseting to "you can dimsiss this message" and not starting the next player's turn properly

**Comment by Villagers654** [comment]
@FrequencyX4 what if when you started a game of uno it automatically created a thread with everyone who opted in to play the game so that it'd be less chat spammy and wouldn't require perms

**Comment by FrequencyX4** [comment]
@Villagers654 I actually like that idea. I'll implement it

**Comment by Villagers654** [comment]
very nice

**Comment by Villagers654** [comment]
Wild card end the game as well as draw 4 cards

**Comment by FrequencyX4** [comment]
Everything's now fixed in [1038d1b](https://github.com/FrequencyX4/Fate/commit/1038d1b7f930c5b619e2c4d2020458914c74545a). Threads will be implemented later

**Comment by Villagers654** [comment]
updated with new issues

**Comment by FrequencyX4** [comment]
Known Issues:
- [ ] #2 cards work on draw 2 and vice versa

**Comment by FrequencyX4** [comment]
@Villagers654 you bitch
